version: "3"
services:
  devops-db:
    image: "postgres:latest"
    container_name: "news-app"
    environment:
      - POSTGRES_USER=aaa
      - POSTGRES_PASSWORD=aaa123
      - POSTGRES_DB=employees
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  devops:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - devops-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://devops-db:5432/news
      - SPRING_DATASOURCE_USERNAME=aaa
      - SPRING_DATASOURCE_PASSWORD=aaa123
    ports:
      - "9090:9090"

volumes:
  postgres-data: